### ISSUE TITLE
Adding @sarasoueidan do your CSS list

### ISSUE THREAD

**Issue by iteles** [timoweiss/people-to-follow#5]
Hi there!

I suggest you add @sarasoueidan to your CSS list, she's pretty fantastic!

```markdown
* Sara Soueidan
  * [![twitter](twitter.png)](https://twitter.com/SaraSoueidan)    
    [![github](github.png)](https://github.com/SaraSoueidan)   
    [![website](website.png)](http://sarasoueidan.com/)
```

**Comment by timoweiss** [comment]
thanks :)

**Comment by SaraSoueidan** [comment]
Thanks you @timoweiss ^^

**Comment by iteles** [comment]
@SaraSoueidan Thank **you** for all the awesome content you share with the world and congratulations on the NET award, very well deserved :)

**Comment by SaraSoueidan** [comment]
@iteles <3
